-- Durable commissioner-override provenance for currently_commissioner_overridden.
-- Forward-only after 20260922160000_week_pick_submission_status.sql.
--
-- Team/game match alone is insufficient (player can change away and back).
-- Transaction-stable now() also makes picks.updated_at vs overridden_at ambiguous.
--
-- Design:
--   * picks.last_commissioner_override_audit_id points at the override that last
--     authored the current selection; cleared on ordinary player team/game mutations.
--   * commissioner_pick_override_audits.audit_seq is a durable monotonic order key
--     (no ctid; UUID id is not chronological).

-- ---------------------------------------------------------------------------
-- Durable audit ordering
-- ---------------------------------------------------------------------------
ALTER TABLE public.commissioner_pick_override_audits
  ADD COLUMN IF NOT EXISTS audit_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'commissioner_pick_override_audits_audit_seq_key'
  ) THEN
    ALTER TABLE public.commissioner_pick_override_audits
      ADD CONSTRAINT commissioner_pick_override_audits_audit_seq_key UNIQUE (audit_seq);
  END IF;
END;
$$;

ALTER TABLE public.commissioner_pick_override_audits
  ALTER COLUMN audit_seq SET NOT NULL;

COMMENT ON COLUMN public.commissioner_pick_override_audits.audit_seq IS
  'Monotonic durable ordering for override audits. Prefer (overridden_at DESC, audit_seq DESC); never ctid.';

-- ---------------------------------------------------------------------------
-- Pick-side provenance pointer
-- ---------------------------------------------------------------------------
ALTER TABLE public.picks
  ADD COLUMN IF NOT EXISTS last_commissioner_override_audit_id UUID
    REFERENCES public.commissioner_pick_override_audits (id);

COMMENT ON COLUMN public.picks.last_commissioner_override_audit_id IS
  'Set by commissioner_override_pick to the audit that authored the current selection; '
  'cleared by ordinary player team/game updates. Not client-writable.';

-- ---------------------------------------------------------------------------
-- Clear / protect provenance on player mutations
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.enforce_regular_pick_insert_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NOT NULL THEN
    IF public.commissioner_override_pick_active() THEN
      IF NEW.submitted_at IS NULL THEN
        NEW.submitted_at := now();
      END IF;
      NEW.updated_at := now();
      RETURN NEW;
    END IF;
    NEW.submitted_at := now();
    NEW.updated_at := now();
    NEW.last_commissioner_override_audit_id := NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.enforce_regular_pick_update_guards()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    -- Service/sync path: preserve override provenance unless explicitly changed.
    RETURN NEW;
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.user_id IS DISTINCT FROM OLD.user_id
     OR NEW.week_id IS DISTINCT FROM OLD.week_id
     OR NEW.submitted_at IS DISTINCT FROM OLD.submitted_at THEN
    RAISE EXCEPTION 'Pick identity fields are immutable'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF public.commissioner_override_pick_active() THEN
    NEW.result_source := 'auto';
    NEW.result_override_reason := NULL;
    NEW.updated_at := now();
    RETURN NEW;
  END IF;

  IF public.is_league_commissioner(public.league_id_for_week(OLD.week_id)) THEN
    IF NEW.team_id IS DISTINCT FROM OLD.team_id
       OR NEW.result IS DISTINCT FROM OLD.result
       OR NEW.result_source IS DISTINCT FROM OLD.result_source
       OR NEW.result_override_reason IS DISTINCT FROM OLD.result_override_reason
       OR NEW.game_id IS DISTINCT FROM OLD.game_id
       OR NEW.last_commissioner_override_audit_id IS DISTINCT FROM OLD.last_commissioner_override_audit_id THEN
      RAISE EXCEPTION 'Use commissioner_override_pick to change regular-season picks'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
  END IF;

  IF NEW.result IS DISTINCT FROM OLD.result
     OR NEW.result_source IS DISTINCT FROM OLD.result_source
     OR NEW.result_override_reason IS DISTINCT FROM OLD.result_override_reason THEN
    RAISE EXCEPTION 'Players may only change team_id on picks'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Any player team/game mutation clears commissioner provenance permanently
  -- until a later commissioner override (even if they change back to the same team).
  IF NEW.team_id IS DISTINCT FROM OLD.team_id
     OR NEW.game_id IS DISTINCT FROM OLD.game_id THEN
    NEW.last_commissioner_override_audit_id := NULL;
  ELSE
    NEW.last_commissioner_override_audit_id := OLD.last_commissioner_override_audit_id;
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.enforce_regular_pick_insert_audit() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.enforce_regular_pick_update_guards() FROM PUBLIC;

-- ---------------------------------------------------------------------------
-- Authoritative override RPC: stamp provenance after writing the audit
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.commissioner_override_pick(
  p_target_user_id UUID,
  p_week_id UUID,
  p_team_id UUID DEFAULT NULL,
  p_reason TEXT DEFAULT NULL,
  p_submitted_requester_id UUID DEFAULT NULL,
  p_submitted_league_id UUID DEFAULT NULL,
  p_submitted_role TEXT DEFAULT NULL,
  p_submitted_result public.pick_result DEFAULT NULL,
  p_submitted_points INTEGER DEFAULT NULL,
  p_submitted_game_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_requester UUID := auth.uid();
  v_league_id UUID;
  v_season_id UUID;
  v_season_year INTEGER;
  v_season_status public.season_status;
  v_week_number INTEGER;
  v_regular_week_count INTEGER;
  v_reason TEXT := btrim(coalesce(p_reason, ''));
  v_existing public.picks%ROWTYPE;
  v_game public.games%ROWTYPE;
  v_new_result public.pick_result;
  v_prev_points INTEGER;
  v_new_points INTEGER;
  v_audit_id UUID;
  v_conflict_week INTEGER;
  v_lock_key BIGINT;
  v_pick_id UUID;
BEGIN
  IF p_submitted_requester_id IS NOT NULL
     OR p_submitted_league_id IS NOT NULL
     OR p_submitted_role IS NOT NULL
     OR p_submitted_result IS NOT NULL
     OR p_submitted_points IS NOT NULL
     OR p_submitted_game_id IS NOT NULL THEN
    NULL;
  END IF;

  IF v_requester IS NULL THEN
    RAISE EXCEPTION 'Authentication required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_reason = '' THEN
    RAISE EXCEPTION 'Override reason is required'
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT s.league_id, s.id, s.year, s.status, s.regular_week_count, w.week_number
  INTO v_league_id, v_season_id, v_season_year, v_season_status, v_regular_week_count, v_week_number
  FROM public.weeks w
  INNER JOIN public.seasons s ON s.id = w.season_id
  WHERE w.id = p_week_id;

  IF v_league_id IS NULL THEN
    RAISE EXCEPTION 'Week not found'
      USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT public.is_league_commissioner(v_league_id) THEN
    RAISE EXCEPTION 'Only an active league commissioner may override picks'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  IF v_season_status IS DISTINCT FROM 'active'::public.season_status THEN
    RAISE EXCEPTION 'Season is not active'
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_week_number < 1 OR v_week_number > v_regular_week_count THEN
    RAISE EXCEPTION 'Week is outside the regular season'
      USING ERRCODE = 'check_violation';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.league_members lm
    WHERE lm.league_id = v_league_id
      AND lm.user_id = p_target_user_id
      AND lm.active = true
  ) THEN
    RAISE EXCEPTION 'Target is not an active member of this league'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  v_lock_key := hashtextextended(
    'commissioner_override/' || v_season_id::text || '/' || p_target_user_id::text,
    0
  );
  PERFORM pg_advisory_xact_lock(v_lock_key);

  SELECT p.* INTO v_existing
  FROM public.picks p
  WHERE p.week_id = p_week_id
    AND p.user_id = p_target_user_id
  FOR UPDATE;

  IF v_existing.id IS NOT NULL THEN
    v_prev_points := public.regular_pick_points_for_result(v_existing.result, v_season_id);
  END IF;

  IF p_team_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.teams t WHERE t.id = p_team_id AND t.active = true
    ) THEN
      RAISE EXCEPTION 'Team not found or inactive'
        USING ERRCODE = 'check_violation';
    END IF;

    SELECT w.week_number INTO v_conflict_week
    FROM public.picks p
    INNER JOIN public.weeks w ON w.id = p.week_id
    WHERE p.user_id = p_target_user_id
      AND p.team_id = p_team_id
      AND w.season_id = v_season_id
      AND p.week_id IS DISTINCT FROM p_week_id
    LIMIT 1;

    IF v_conflict_week IS NOT NULL THEN
      RAISE EXCEPTION 'Team already used by this player in week %', v_conflict_week
        USING ERRCODE = 'check_violation',
              DETAIL = format('conflicting_week_number=%s', v_conflict_week);
    END IF;

    v_game := public.regular_team_game_for_override(v_season_year, v_week_number, p_team_id);
    v_new_result := public.derive_regular_pick_result_from_game(v_game, p_team_id);
    v_new_points := public.regular_pick_points_for_result(v_new_result, v_season_id);
  ELSIF v_existing.id IS NULL THEN
    RAISE EXCEPTION 'No pick to clear for this player and week'
      USING ERRCODE = 'no_data_found';
  END IF;

  BEGIN
    PERFORM set_config('app.commissioner_override_pick', '1', true);

    IF p_team_id IS NULL THEN
      DELETE FROM public.picks WHERE id = v_existing.id;

      INSERT INTO public.commissioner_pick_override_audits (
        commissioner_user_id, target_user_id, league_id, season_id, week_id, week_number,
        previous_team_id, previous_game_id, previous_result, previous_points,
        new_team_id, new_game_id, new_result, new_points, cleared, reason
      ) VALUES (
        v_requester, p_target_user_id, v_league_id, v_season_id, p_week_id, v_week_number,
        v_existing.team_id, v_existing.game_id, v_existing.result, v_prev_points,
        NULL, NULL, NULL, NULL, true, v_reason
      )
      RETURNING id INTO v_audit_id;

      PERFORM set_config('app.commissioner_override_pick', '', true);

      RETURN jsonb_build_object(
        'audit_id', v_audit_id,
        'cleared', true,
        'pick_id', NULL,
        'week_id', p_week_id,
        'user_id', p_target_user_id,
        'team_id', NULL,
        'game_id', NULL,
        'result', NULL,
        'points', 0,
        'week_number', v_week_number
      );
    END IF;

    IF v_existing.id IS NOT NULL THEN
      UPDATE public.picks
      SET team_id = p_team_id,
          game_id = v_game.id,
          result = v_new_result,
          result_source = 'auto',
          result_override_reason = NULL,
          last_commissioner_override_audit_id = NULL,
          updated_at = now()
      WHERE id = v_existing.id
      RETURNING id INTO v_pick_id;

      IF v_pick_id IS NULL THEN
        RAISE EXCEPTION 'Pick update failed'
          USING ERRCODE = 'data_exception';
      END IF;
    ELSE
      INSERT INTO public.picks (
        week_id, user_id, team_id, game_id, result, result_source, result_override_reason,
        last_commissioner_override_audit_id
      ) VALUES (
        p_week_id, p_target_user_id, p_team_id, v_game.id, v_new_result, 'auto', NULL,
        NULL
      )
      RETURNING id INTO v_pick_id;

      IF v_pick_id IS NULL THEN
        RAISE EXCEPTION 'Pick insert failed'
          USING ERRCODE = 'data_exception';
      END IF;
    END IF;

    INSERT INTO public.commissioner_pick_override_audits (
      commissioner_user_id, target_user_id, league_id, season_id, week_id, week_number,
      previous_team_id, previous_game_id, previous_result, previous_points,
      new_team_id, new_game_id, new_result, new_points, cleared, reason
    ) VALUES (
      v_requester, p_target_user_id, v_league_id, v_season_id, p_week_id, v_week_number,
      v_existing.team_id, v_existing.game_id, v_existing.result, v_prev_points,
      p_team_id, v_game.id, v_new_result, v_new_points, false, v_reason
    )
    RETURNING id INTO v_audit_id;

    UPDATE public.picks
    SET last_commissioner_override_audit_id = v_audit_id,
        updated_at = now()
    WHERE id = v_pick_id;

    PERFORM set_config('app.commissioner_override_pick', '', true);

    RETURN jsonb_build_object(
      'audit_id', v_audit_id,
      'cleared', false,
      'pick_id', v_pick_id,
      'week_id', p_week_id,
      'user_id', p_target_user_id,
      'team_id', p_team_id,
      'game_id', v_game.id,
      'result', v_new_result,
      'points', v_new_points,
      'week_number', v_week_number,
      'game_status', v_game.status
    );
  EXCEPTION
    WHEN OTHERS THEN
      PERFORM set_config('app.commissioner_override_pick', '', true);
      RAISE;
  END;
END;
$$;

REVOKE ALL ON FUNCTION public.commissioner_override_pick(
  UUID, UUID, UUID, TEXT, UUID, UUID, TEXT, public.pick_result, INTEGER, UUID
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.commissioner_override_pick(
  UUID, UUID, UUID, TEXT, UUID, UUID, TEXT, public.pick_result, INTEGER, UUID
) FROM anon;
REVOKE ALL ON FUNCTION public.commissioner_override_pick(
  UUID, UUID, UUID, TEXT, UUID, UUID, TEXT, public.pick_result, INTEGER, UUID
) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.commissioner_override_pick(
  UUID, UUID, UUID, TEXT, UUID, UUID, TEXT, public.pick_result, INTEGER, UUID
) TO authenticated;

-- ---------------------------------------------------------------------------
-- Submission status: provenance via stamped audit id (no ctid)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.week_pick_submission_status(p_week_id UUID)
RETURNS TABLE (
  user_id UUID,
  has_pick BOOLEAN,
  currently_commissioner_overridden BOOLEAN
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_requester UUID := auth.uid();
  v_league_id UUID;
BEGIN
  IF v_requester IS NULL THEN
    RAISE EXCEPTION 'Authentication required'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT s.league_id
  INTO v_league_id
  FROM public.weeks w
  INNER JOIN public.seasons s ON s.id = w.season_id
  WHERE w.id = p_week_id;

  IF v_league_id IS NULL THEN
    RAISE EXCEPTION 'Week not found'
      USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT public.is_active_league_member(v_league_id) THEN
    RAISE EXCEPTION 'Not an active member of this league'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN QUERY
  WITH active_members AS (
    SELECT lm.user_id
    FROM public.league_members lm
    WHERE lm.league_id = v_league_id
      AND lm.active = true
  ),
  pick_rows AS (
    SELECT
      p.user_id,
      p.team_id,
      p.game_id,
      p.last_commissioner_override_audit_id
    FROM public.picks p
    WHERE p.week_id = p_week_id
  )
  SELECT
    m.user_id,
    (pr.user_id IS NOT NULL) AS has_pick,
    (
      pr.user_id IS NOT NULL
      AND pr.last_commissioner_override_audit_id IS NOT NULL
      AND a.id IS NOT NULL
      AND a.cleared = false
      AND a.new_team_id IS NOT NULL
      AND pr.team_id = a.new_team_id
      AND pr.game_id IS NOT DISTINCT FROM a.new_game_id
      AND pr.last_commissioner_override_audit_id = a.id
    ) AS currently_commissioner_overridden
  FROM active_members m
  LEFT JOIN pick_rows pr ON pr.user_id = m.user_id
  LEFT JOIN public.commissioner_pick_override_audits a
    ON a.id = pr.last_commissioner_override_audit_id
  ORDER BY m.user_id;
END;
$$;

COMMENT ON FUNCTION public.week_pick_submission_status(UUID) IS
  'Active league members only: user_id, has_pick, currently_commissioner_overridden. '
  'Override flag requires picks.last_commissioner_override_audit_id to match a non-cleared '
  'audit whose team/game still equal the current pick (player mutations clear the stamp).';

REVOKE ALL ON FUNCTION public.week_pick_submission_status(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.week_pick_submission_status(UUID) FROM anon;
REVOKE ALL ON FUNCTION public.week_pick_submission_status(UUID) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.week_pick_submission_status(UUID) TO authenticated;
